<?php

$labels = array();
$labels['scheduled_send'] = 'Scheduled Send';
$labels['scheduled_send_time'] = 'Schedule Time';
$labels['cancel_scheduled_email'] = 'Cancel Scheduled Email';
$labels['scheduled_email_saved'] = 'Email scheduled for %s';
$labels['scheduled_email_canceled'] = 'Email canceled';
$labels['invalid_time'] = 'Invalid time. Please choose a future time.';
$labels['scheduled_email_error'] = 'Error saving scheduled email.';
$labels['scheduled_email_cancel_error'] = 'Error canceling scheduled email.';